### ISSUE TITLE
Lang file for sponge plugin

### ISSUE THREAD

**Issue by iTeeLion** [djxy/ServerBackup#2]
Hi! Add the lang file/class please. I wanna translate your plugin ^_^

**Comment by djxy** [comment]
Which files?

**Comment by iTeeLion** [comment]
Which contain a translation into another language

**Comment by djxy** [comment]
If you want to translate the plugin you have to go [here](https://github.com/djxy/PermissionManager/blob/master/translations/en_US.hocon)(This is the translation in english). Copy everything and create a new file with the english translation.

By example if you translate this line `promotePlayer="You promote {player} as {promotion}."` you have some elements to understand. First, `promotePlayer` is the name of the translation, don't change that because the plugin use this to retrieve the translation. Second, `"You promote {player} as {promotion}."` is the text to translate. In the text there is ` {player}` and `{promotion}`. This is like a variable for the plugin, `{player}` will be changed for the player's name and `{promotion}` by the promotion's name.

So, to translate the plugin, you have to do this `promotePlayer="portuguese portuguese {player} portuguese {promotion}."` and my plugin will understand. You can change the order of the variables like this`promotePlayer="{promotion} portuguese portuguese {player} portuguese."` and everything will works.

If you need help, ask me.
